version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edu_video_hub_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    working_dir: /app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3001:80"
    depends_on:
      - backend
  
  

volumes:
  postgres-data:
